version: '3.8'

services:
  # Сервис для базы данных PostgreSQL
  dockins-db:
    image: postgres:17.4
    container_name: dockins-db
    environment:
      POSTGRES_USER: ${DOCKINS_DB_USERNAME}
      POSTGRES_PASSWORD: ${DOCKINS_DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dockins-network
    ports:
      - "5432:5432"

  # Сервис для вашего приложения Spring Boot
  dockins-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockins-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8080
      DOCKINS_DB_URL: jdbc:postgresql://dockins-db:5432/postgres
      DOCKINS_MAIL_ENABLED: true
      DOCKINS_MAIL_CONFIRMATION_ENABLED: false
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - dockins-db
    networks:
      - dockins-network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

networks:
  dockins-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
